version: '3.7'
services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=maissuavida
    volumes:
      - maissuavida_pg_data:/bitnami/postgresql

  node:
    image: node:20.11.0
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    ports:
      - '3333:3333'
    depends_on:
      - postgres

volumes:
  maissuavida_pg_data: